joint_name_to_servo_id: {
  FrontLeftJoint0: {id: 15, direction: 1, offset: 0},
  FrontLeftJoint1: {id: 21, direction: 1, offset: 0},
  FrontLeftJoint2: {id: 23, direction: -1, offset: 0},
  FrontLeftJoint3: {id: 33, direction: -1, offset: 0},
  FrontLeftJoint4: {id: 35, direction: 1, offset: 0},
  FrontRightJoint0: {id: 1, direction: -1, offset: 0},
  FrontRightJoint1: {id: 3, direction: 1, offset: 0},
  FrontRightJoint2: {id: 5, direction: -1, offset: 0},
  FrontRightJoint3: {id: 7, direction: -1, offset: 0},
  FrontRightJoint4: {id: 9, direction: 1, offset: 0},
  RearRightJoint0: {id: 0, direction: 1, offset: 0},
  RearRightJoint1: {id: 2, direction: 1, offset: 0},
  RearRightJoint2: {id: 4, direction: -1, offset: 0},
  RearRightJoint3: {id: 6, direction: -1, offset: 0},
  RearRightJoint4: {id: 8, direction: 1, offset: 0},
  RearLeftJoint0: {id: 14, direction: -1, offset: 0},
  RearLeftJoint1: {id: 20, direction: 1, offset: 0},
  RearLeftJoint2: {id: 22, direction: -1, offset: 0},
  RearLeftJoint3: {id: 32, direction: -1, offset: 0},
  RearLeftJoint4: {id: 34, direction: 1, offset: 0},
}